name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Runs workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS CLI Installation
        run: aws --version  

      - name: Upload APK to AWS S3
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://${{ secrets.S3_BUCKET_NAME }}/app-release.apk --acl public-read

      - name: Print APK Download Link
        run: echo "APK is available at: https://${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com/app-release.apk"
