name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Latest Flutter Docker Image
        run: docker pull ghcr.io/flutter/flutter:latest

      - name: Run Flutter Build & Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ghcr.io/flutter/flutter:latest bash -c "
          flutter pub get &&
          flutter test &&
          flutter build apk --release"

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          output: trivy-report.txt   # ✅ FIXED (removed extra quote)

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "FlutterApp"
          format: "HTML"
          out: "dependency-check-report"

      - name: Install k6
        run: sudo snap install k6

      - name: Run k6 Performance Test
        run: |
          mkdir -p reports
          k6 run test/load_test.js --out json=reports/k6-performance-test-report.json || true

      - name: Upload Reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: security-and-performance-reports
          path: |
            trivy-report.txt
            dependency-check-report
            reports/k6-performance-test-report.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload APK and Reports to S3
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://bus-route-finder-apk/flutter-app/app-release.apk
          aws s3 cp trivy-report.txt s3://bus-route-finder-apk/security-reports/trivy-report.txt
          aws s3 cp dependency-check-report s3://bus-route-finder-apk/security-reports/dependency-check-report/ --recursive
          aws s3 cp reports/k6-performance-test-report.json s3://bus-route-finder-apk/performance-reports/k6-performance-test-report.json
