name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

  security_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          output: 'trivy-report.txt'

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "FlutterApp"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Security Reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy-report.txt
            dependency-check-report

  load_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install K6 for Load Testing
        run: sudo snap install k6

      - name: Run K6 Load Test
        run: |
          k6 run tests/load_test.js --out json=reports/k6-report.json || true

      - name: Upload K6 Load Test Report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: k6-load-test-report
          path: reports/k6-report.json

  upload_s3:
    runs-on: ubuntu-latest
    needs: [build, security_scan, load_test]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload APK to S3
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://bus-route-finder-apk/flutter-app/app-release.apk

      - name: Upload Security Reports to S3
        run: |
          aws s3 cp trivy-report.txt s3://bus-route-finder-apk/security-reports/trivy-report.txt
          aws s3 cp dependency-check-report s3://bus-route-finder-apk/security-reports/dependency-check-report/ --recursive

      - name: Upload K6 Load Test Report to S3
        run: |
          aws s3 cp reports/k6-report.json s3://bus-route-finder-apk/performance-reports/k6-report.json
