name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Flutter & Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Clean Project
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME manually
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Verify JAVA_HOME
        run: echo $JAVA_HOME && ls -l $JAVA_HOME/bin

      - name: Run OWASP Dependency Check
        run: |
          apt-get update && apt-get install -y unzip
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip
          unzip dependency-check-8.3.1-release.zip
          mkdir -p dependency-check-report
          ./dependency-check/bin/dependency-check.sh --project "FlutterApp" --scan . --format "ALL" --out dependency-check-report/

      - name: Upload OWASP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Dependency-Check-Report
          path: dependency-check-report/

  test-build-upload:
    runs-on: ubuntu-latest
    needs: security-scan
    container:
      image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME manually
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Verify JAVA_HOME
        run: echo $JAVA_HOME && ls -l $JAVA_HOME/bin

      - name: Run Tests
        run: flutter test

      - name: Upgrade Gradle Wrapper
        run: |
          chmod +x android/gradlew
          ./android/gradlew wrapper --gradle-version 8.4 --distribution-type all

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          apt-get update && apt-get install -y awscli
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://$S3_BUCKET_NAME/app-release.apk --acl public-read

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: "Latest Release"
          body: "[Download APK](https://${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com/app-release.apk)"
          token: ${{ secrets.GH_PAT }}
