name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install Dependencies
        run: flutter pub get

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: flutter test

  build_apk:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to S3
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://bus-route-finder-apk/flutter-app/app-release.apk

  security_scan:
    runs-on: ubuntu-latest
    needs: build_apk
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          output: 'trivy-report.txt'

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "FlutterApp"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Security Reports to S3
        run: |
          aws s3 cp trivy-report.txt s3://bus-route-finder-apk/security-reports/trivy-report.txt
          aws s3 cp dependency-check-report s3://bus-route-finder-apk/security-reports/dependency-check-report/ --recursive

  performance_test:
    runs-on: ubuntu-latest
    needs: build_apk
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install K6 for Load Testing
        run: sudo snap install k6

      - name: Run K6 Load Test
        run: |
          k6 run tests/load_test.js --out json=reports/k6-report.json || true

      - name: Upload K6 Load Test Report to S3
        run: |
          aws s3 cp reports/k6-report.json s3://bus-route-finder-apk/performance-reports/k6-report.json
